### ISSUE TITLE
Please ask how much memory is used？

### ISSUE THREAD

**Issue by intjun** [xmba15/torch_cpp#1]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.81 GiB total capacity; 1.45 GiB already allocated; 51.69 MiB free; 1.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by xmba15** [comment]
Which GPU are you using? how much GB?

**Comment by intjun** [comment]
> Which GPU are you using? how much GB?

rtx3060,4G

**Comment by xmba15** [comment]
@intjun 
I checked on my env, when running superglue sample the total amount of memory needed is 2.5GB. So your GPU is enough to run the gpu sample.

Maybe you suffered from this problem?
https://github.com/pytorch/pytorch/issues/17095

I also made the input shape for superpoint dynamic as you can see in this PR.
Reduce the input shape to, for example, 300x400 will reduce the GPU memory needed to about only 1.5GB.
https://github.com/xmba15/torch_cpp/pull/2
