### ISSUE TITLE
Difference with implementation of SuperPoint SLAM

### ISSUE THREAD

**Issue by hellovuong** [xmba15/torch_cpp#3]
Hello,
Thank you so much for this implementation. I am new to Deep Learning and PyTorch in general, so my question may be a bit naive. 
I notice there are differences in SuperPoint implementation between yours and[ SuperPoint SLAM](https://github.com/KinglittleQ/SuperPoint_SLAM), such as yours doesn't have `structure SuperPoint` and define its conv layers like [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/4bf56e209856f3eed4b186874b2ab7e4c3c0e82b/src/SuperPoint.cc#L16). Is it have any pros and cons between this two implementation?
I Hope can hear from you!

**Comment by xmba15** [comment]
@hellovuong 
- The implementation in SuperPoint SLAM used [torch frontend](https://pytorch.org/cppdocs/frontend.html), which means it is just a translation of python forward function to C++ forward function.
- My implementation used [torch script](https://pytorch.org/docs/stable/jit.html). Torch script creates a serialization of python process. You do not need to manually define the model and forward function in C++ this way.

**Comment by hellovuong** [comment]
Great, thank you! 
One more question, I saw the `visual odometry` branch, are you working on it, I had experience with Visual SLAM and ORB_SLAM, do you need any help or contribution with the branch?

**Comment by xmba15** [comment]
@hellovuong I am just coding that branch on my free time now. Not so much work I think I could share now, except that I might need a reviewer once I finish.

Btw, if you are interested, can you contribute a sample for SuperPoint + SuperGlue visual SLAM? I will review the code once you finish. If you are still a student (?), a comparison of ORB SLAM vs SuperPoint SuperGlue SLAM might be a good topic idea for a domestic conference, as the author of SuperPoint SLAM claimed that SuperPoint (SLAM) is not superior to ORB (SLAM).

**Comment by hellovuong** [comment]
Great thank you for the input!
