### ISSUE TITLE
how to build the source code?

### ISSUE THREAD

**Issue by doublepoints** [xmba15/torch_cpp#5]
Hi, I am not so familiar with the building of c++, if possible, would you please show some building details?
Thank you very much.

**Comment by xmba15** [comment]
Hi @doublepoints 
I would assume that you are building for a CPU environment. (For GPU env, the steps are quite similar, please explore yourself).
- First of all: install libtorch with this script:
https://github.com/xmba15/dockerfiles/blob/master/torch_cpp/scripts/install_libtorch.bash

- Install opencv:
```bash
sudo apt-get install -y --no-install-recommends \
    libopencv-dev
```

- Download weights in this release:
https://github.com/xmba15/torch_cpp/releases/tag/0.0.1

- Build library and apps:
```bash
cd /path/to/torch_cpp
make apps
```

- Test the matching app
```bash
./build/examples/match_images_superglue/match_images_superglue_app path/to/superpoint_model.pt path/to/superglue_model.pt ./data/images/VisionCS_0a.png ./data/images/VisionCS_0b.png
```
